// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
<<<<<<< HEAD
        return macos;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> 93b11f763332b0d580854ccf075f38e09e63d8c8
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcRT2w_tko9LAxfTw-mM8L3DRwCWpYkk',
    appId: '1:1014030563010:web:c4c3f379bbd1f8487a6d5b',
    messagingSenderId: '1014030563010',
    projectId: 'mindgauge-13cf8',
    authDomain: 'mindgauge-13cf8.firebaseapp.com',
    storageBucket: 'mindgauge-13cf8.firebasestorage.app',
    measurementId: 'G-LH9KKT1WSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgKRDL0d3em4L6_eOvIOlE_S29kL8BJo',
    appId: '1:1014030563010:android:7d78c42b8cbc6e537a6d5b',
    messagingSenderId: '1014030563010',
    projectId: 'mindgauge-13cf8',
    storageBucket: 'mindgauge-13cf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRr7oLXfosL4YtY5m_ZagS2xUVFEDfvI',
    appId: '1:1014030563010:ios:0c5c3a15d7d7e9127a6d5b',
    messagingSenderId: '1014030563010',
    projectId: 'mindgauge-13cf8',
    storageBucket: 'mindgauge-13cf8.firebasestorage.app',
    iosBundleId: 'com.example.mindGauge',
  );

<<<<<<< HEAD
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRr7oLXfosL4YtY5m_ZagS2xUVFEDfvI',
    appId: '1:1014030563010:ios:0c5c3a15d7d7e9127a6d5b',
    messagingSenderId: '1014030563010',
    projectId: 'mindgauge-13cf8',
    storageBucket: 'mindgauge-13cf8.firebasestorage.app',
    iosBundleId: 'com.example.mindGauge',
  );

=======
>>>>>>> 93b11f763332b0d580854ccf075f38e09e63d8c8
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgcRT2w_tko9LAxfTw-mM8L3DRwCWpYkk',
    appId: '1:1014030563010:web:dc2d2710e0bc7a647a6d5b',
    messagingSenderId: '1014030563010',
    projectId: 'mindgauge-13cf8',
    authDomain: 'mindgauge-13cf8.firebaseapp.com',
    storageBucket: 'mindgauge-13cf8.firebasestorage.app',
    measurementId: 'G-SJK1JPYFNL',
  );
}
